FROM golang:1.10.4-alpine
RUN apk --no-cache add ca-certificates graphviz binutils git
WORKDIR /go/src/github.com/cgilling/pprof-me
RUN CGO_ENABLED=0 GOOS=linux go get github.com/google/pprof
COPY . ./
RUN go get -t ./...
RUN go install ./...
CMD ["go", "test", "./..."]